export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_REQUEST_SUCCES = 'FETCH_USERS_REQUEST_SUCCES'
export const FETCH_USERS_REQUEST_FAILURE = 'FETCH_USERS_REQUEST_FAILURE'
